SIMULATION:
  START: 36000
  END: 43200
  STEP: 6

REQUEST:
  FILE: './data/order.pickle'
  CHECK_ITINERARY: False
  CONSTRAINTS:
    max_assign_time: 600
    max_pickup_time: 600
    max_travel_time_mul: 1.5
    max_travel_dis_mul: 1.5
  BEHAVIORS:
    max_assign_time: 180
    max_pickup_time: 300
    cancel_prob_assign: 0.6
    cancel_prob_pickup: 0.1
    max_tol_vehicle_capacity: 4
    max_tol_price: None

VEHICLE:
  FILE: './data/driver_info.pickle'
  NUM: 500
  VELOCITY: 6
  MAXCAPACITY: 1
  PlanPathMethod: 'NearestFirst'
  REPOSITION:
    TYPE: True
    METHOD: 'Random'
    
ENVIRONMENT:
  TYPE: 'NY'
  NY:
    RoadFile: './data/graph.graphml'
    TravelTimeFile: None
    TravelDisFile: None
  TOY:
    NumNode: 21
    DisPerLine: 500
  CONSIDER_ITINERARY: False
  MANHATTAN_DIS_MUL: 1.2
  CONSIDER_CONGESTION: False